// Code generated by rclgo-gen. DO NOT EDIT.

package elevator_msgs_msg

/*
#cgo LDFLAGS: "-L/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/lib" "-Wl,-rpath=/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/lib"
#cgo LDFLAGS: "-L/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/lib" "-Wl,-rpath=/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/lib"
#cgo LDFLAGS: "-L/opt/ros/jazzy/lib" "-Wl,-rpath=/opt/ros/jazzy/lib"

#cgo LDFLAGS: -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lelevator_msgs__rosidl_typesupport_c -lelevator_msgs__rosidl_generator_c

#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/action_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/builtin_interfaces"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/example_interfaces"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/geometry_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/rcutils"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/rosidl_dynamic_typesupport"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/sensor_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/service_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/std_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/std_srvs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/test_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/type_description_interfaces"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/greeting_msgs/include/elevator_msgs"

#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/action_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/builtin_interfaces"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/example_interfaces"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/geometry_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/rcutils"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/rosidl_dynamic_typesupport"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/sensor_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/service_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/std_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/std_srvs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/test_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/type_description_interfaces"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/home/ole/go_workspace/elevator_msgs/install/elevator_msgs/include/elevator_msgs"

#cgo CFLAGS: "-I/opt/ros/jazzy/include/action_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/builtin_interfaces"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/example_interfaces"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/geometry_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/rcutils"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/rosidl_dynamic_typesupport"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/sensor_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/service_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/std_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/std_srvs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/test_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/type_description_interfaces"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/opt/ros/jazzy/include/elevator_msgs"
*/
import "C"
